//@ui5-bundle com/sap/iOSExternalIPAInstall/Component-preload.js
jQuery.sap.registerPreloadedModules({
"version":"2.0",
"modules":{
	"com/sap/iOSExternalIPAInstall/Component.js":function(){sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","com/sap/iOSExternalIPAInstall/model/models"],function(e,t,i){"use strict";return e.extend("com.sap.iOSExternalIPAInstall.Component",{metadata:{manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);this.getRouter().initialize();this.setModel(i.createDeviceModel(),"device")}})});
},
	"com/sap/iOSExternalIPAInstall/controller/App.controller.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller"],function(n){"use strict";return n.extend("com.sap.iOSExternalIPAInstall.controller.App",{onInit:function(){},downloadApp:function(n){window.location.href="itms-services://?action=download-manifest&amp;url=https://ipaexternalinstallation-rnzihte43v.dispatcher.hana.ondemand.com/assets/app.plist";sap.m.MessageToast.show("Thank you for downloading...")}})});
},
	"com/sap/iOSExternalIPAInstall/i18n/i18n.properties":'title=GuideToTech\nappTitle=iOSExternalIPAInstall\nappDescription=App Description\ndesc=Click to start Installing\nversion=1.0.5\nappOpen=Open this page in Safari on your iOS device to be able to install the app\nidentifier=com.sap.analytics.AnalyticsGuide\nsize=29.00 MB\niOSversion=12.0\ndevice=iPhone\narch=arm64',
	"com/sap/iOSExternalIPAInstall/manifest.json":'{"_version":"1.12.0","sap.app":{"id":"com.sap.iOSExternalIPAInstall","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"1.0.0"},"title":"{{appTitle}}","description":"{{appDescription}}","sourceTemplate":{"id":"ui5template.basicSAPUI5ApplicationProject","version":"1.40.12"}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":false,"rootView":{"viewName":"com.sap.iOSExternalIPAInstall.view.App","type":"XML","async":true,"id":"App"},"dependencies":{"minUI5Version":"1.65.6","libs":{"sap.ui.layout":{},"sap.ui.core":{},"sap.m":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"com.sap.iOSExternalIPAInstall.i18n.i18n"}}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","async":true,"viewPath":"com.sap.iOSExternalIPAInstall.view","controlAggregation":"pages","controlId":"app","clearControlAggregation":false},"routes":[{"name":"RouteApp","pattern":"RouteApp","target":["TargetApp"]}],"targets":{"TargetApp":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"App","viewName":"App"}}}},"sap.platform.hcp":{"uri":"webapp","_version":"1.1.0"}}',
	"com/sap/iOSExternalIPAInstall/model/models.js":function(){sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"com/sap/iOSExternalIPAInstall/view/App.view.xml":'<mvc:View xmlns:mvc="sap.ui.core.mvc" xmlns="sap.m" controllerName="com.sap.iOSExternalIPAInstall.controller.App" displayBlock="true"><Shell id="shell"><App id="app"><pages><Page id="page" title="{i18n>title}" showHeader="false"><content><StandardListItem type="Active" title="GuidetoTech" description="v{i18n>version}" icon="logo.png" id="item4"/><OverflowToolbar width="100%" id="toolbar1"/><HBox class="sapUiSmallMargin"><items><Label text="DOWNLOAD"/></items></HBox><StandardListItem type="Navigation" title="Download Application" description="{i18n>desc}" icon="sap-icon://download-from-cloud" id="downloadApp" press="downloadApp"/><HBox class="sapUiTinyMargin"><items><Label text="{i18n>appOpen}" wrapping="true"/></items></HBox><OverflowToolbar width="100%" id="toolbar2"/><HBox class="sapUiSmallMargin"><items><Label text="APP DETAILS"/></items></HBox><DisplayListItem type="Active" label="Bundle identifier" value="{i18n>identifier}"/><DisplayListItem type="Active" label="Size" value="{i18n>size}"/><DisplayListItem type="Active" label="Minimum iOS version" value="{i18n>iOSversion}"/><DisplayListItem type="Active" label="Device family" value="{i18n>device}"/><DisplayListItem type="Active" label="Supported architectures" value="{i18n>arch}"/></content></Page></pages></App></Shell></mvc:View>'
}});
