//@ui5-bundle com/sap/image-preview-with-file-uploader/Component-preload.js
jQuery.sap.registerPreloadedModules({
"version":"2.0",
"modules":{
	"com/sap/image-preview-with-file-uploader/Component.js":function(){sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","com/sap/image-preview-with-file-uploader/model/models"],function(e,i,t){"use strict";return e.extend("com.sap.image-preview-with-file-uploader.Component",{metadata:{manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);this.getRouter().initialize();this.setModel(t.createDeviceModel(),"device")}})});
},
	"com/sap/image-preview-with-file-uploader/controller/App.controller.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller"],function(e){"use strict";return e.extend("com.sap.image-preview-with-file-uploader.controller.App",{onInit:function(){},onEditImage:function(e){if(e.getParameter("action")==="Press"){this.getView().byId("fileUploader-label").getDomRef().click()}else if(e.getParameter("action")==="Remove"){this.getView().byId("actionIcon").setSrc("sap-icon://add");this.getView().byId("image").setSubheader("No Image Selected");this.getView().byId("image").setBackgroundImage("")}},onChangeImage:function(e){if(e.getSource().oFileUpload.files.length>0){var t=e.getSource().oFileUpload.files[0];var i=URL.createObjectURL(t);this.getView().byId("image").setBackgroundImage(i);this.getView().byId("image").setSubheader("");this.getView().byId("actionIcon").setSrc("sap-icon://edit")}}})});
},
	"com/sap/image-preview-with-file-uploader/i18n/i18n.properties":'title=Title\nappTitle=image-preview-with-file-uploader\nappDescription=App Description',
	"com/sap/image-preview-with-file-uploader/manifest.json":'{"_version":"1.12.0","sap.app":{"id":"com.sap.image-preview-with-file-uploader","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"1.0.0"},"title":"{{appTitle}}","description":"{{appDescription}}","sourceTemplate":{"id":"ui5template.basicSAPUI5ApplicationProject","version":"1.40.12"}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":false,"rootView":{"viewName":"com.sap.image-preview-with-file-uploader.view.App","type":"XML","async":true,"id":"App"},"dependencies":{"minUI5Version":"1.65.6","libs":{"sap.ui.layout":{},"sap.ui.core":{},"sap.m":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"com.sap.image-preview-with-file-uploader.i18n.i18n"}}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","async":true,"viewPath":"com.sap.image-preview-with-file-uploader.view","controlAggregation":"pages","controlId":"app","clearControlAggregation":false},"routes":[{"name":"RouteApp","pattern":"RouteApp","target":["TargetApp"]}],"targets":{"TargetApp":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"App","viewName":"App"}}}}}',
	"com/sap/image-preview-with-file-uploader/model/models.js":function(){sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"com/sap/image-preview-with-file-uploader/view/App.view.xml":'<mvc:View xmlns:mvc="sap.ui.core.mvc" xmlns:u="sap.ui.unified" xmlns="sap.m"\n\tcontrollerName="com.sap.image-preview-with-file-uploader.controller.App" displayBlock="true"><Shell id="shell"><App id="app"><pages><Page id="page" title="{i18n>title}"><content><VBox><items><u:FileUploader name="uploadFile" change="onChangeImage" id="fileUploader" class="hiddenControls" fileType="jpg,png,jpeg" sendXHR="true"/><Label labelFor="fileUploader-fu" id="fileUploader-label" class="hiddenControls"/><GenericTile class="imagePreview" press="onEditImage" id="image" scope="Actions" subheader="No Image Selected"><tileContent><TileContent id="iconContent"><content><sap.ui.core:Icon xmlns:sap.ui.core="sap.ui.core" src="sap-icon://add" size="2em" id="actionIcon" class="actionIcon"/></content></TileContent></tileContent></GenericTile></items></VBox></content></Page></pages></App></Shell></mvc:View>'
}});
